<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>Lecturas</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>23</maven.compiler.source>
        <maven.compiler.target>23</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <dependencies>

        <!-- Source: https://mvnrepository.com/artifact/org.projectlombok/lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.42</version>
        </dependency>
<!-- Project Lombok es una librería de Java que reduce código repetitivo (boilerplate)
generando automáticamente métodos comunes en tiempo de compilación.
Se usa principalmente para evitar escribir:
getters         setters         constructores
toString()       equals() y hashCode()       builders -->

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.16.0</version>
        </dependency>
        <!-- jackson-databind es una librería de Jackson usada para convertir
objetos Java a JSON y viceversa. Permite:
Serializar: objeto Java → JSON.
Deserializar: JSON → objeto Java.
Se usa muchísimo en APIs REST, especialmente con frameworks como Spring Boot.
    Ejemplo:
ObjectMapper mapper = new ObjectMapper();
User user = mapper.readValue(json, User.class);
SU DIFERENCIA FRENTE A JSON.ORG ES QUE JSON ES UN MAPEADOR Y JACKSON HACE LA PETICIÓN,
LA DEVUELVE Y LA CONVIERTE-->

        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.3.1</version>
        </dependency>
<!-- javax.xml.bind (JAXB) es una API de Java para convertir entre objetos Java y XML.
(Estaba incluida en el JDK hasta Java 8, pero desde Java 9+ se separó y hay que añadirla como dependencia)
Permite:
Marshalling: objeto Java → XML.
Unmarshalling: XML → objeto Java.
    Ejemplo:
JAXBContext context = JAXBContext.newInstance(User.class);
Unmarshaller um = context.createUnmarshaller();
User user = (User) um.unmarshal(new File("user.xml")); -->

        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-runtime</artifactId>
            <version>2.3.9</version>
        </dependency>
<!-- org.glassfish.jaxb es la implementación concreta de JAXB mantenida por GlassFish.
(javax.xml.bind es solo la API, pero necesitas una implementación para que funcione).
org.glassfish.jaxb proporciona esa implementación para Java 9+ y Jakarta.-->

    </dependencies>

</project>